server:
  port: 1111

  logging:
    level:
      org:
        springframework: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"



        spring:
          security:
            user:
              name: admin
              password: secret
              roles: ACTUATOR